spring:
  datasource:
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leizu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 600000
      connection-timeout: 600000  #开发时预设10分钟
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false  # 开发时配置

#server:
#  servlet:
#    context-path: /leizu    # 設定訪問路徑

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.chloe.leizu_pro.bean
  configuration:
    map-underscore-to-camel-case: true

